using System.Globalization;
using System.IO;
using System.Windows.Data;
using System.Windows.Media.Imaging;

namespace PhotoWell.Desktop.Converters;

/// <summary>
/// Converts a file-system path string to a BitmapImage capped at 1600px wide.
/// Always loads fresh from disk (IgnoreImageCache) so rotated/regenerated thumbnails
/// are picked up immediately without a stale cached copy.
///
/// No EXIF orientation is applied here: every path fed to this converter is a
/// thumbnail or face-crop file generated by ThumbnailService, which already bakes
/// orientation into the pixels and resets the EXIF tag to 1 (normal). Applying EXIF
/// correction again would double-rotate photos whose thumbnails still carry the
/// original tag. The full-res viewer has its own loader that handles EXIF + UserRotation.
/// </summary>
public class PathToImageSourceConverter : IValueConverter
{
    public object? Convert(object? value, Type targetType, object? parameter, CultureInfo culture)
    {
        if (value is not string path || !File.Exists(path)) return null;
        try
        {
            var bmp = new BitmapImage();
            bmp.BeginInit();
            bmp.UriSource        = new Uri(path);
            bmp.DecodePixelWidth = 1600;
            bmp.CacheOption      = BitmapCacheOption.OnLoad;
            bmp.CreateOptions    = BitmapCreateOptions.IgnoreImageCache;
            bmp.EndInit();
            bmp.Freeze();
            return bmp;
        }
        catch { return null; }
    }

    public object? ConvertBack(object? value, Type targetType, object? parameter, CultureInfo culture)
        => throw new NotSupportedException();
}
