using Xunit;
using PhotoIQPro.Core.Models;

namespace PhotoIQPro.Tests;

// ── Tag model ─────────────────────────────────────────────────────────────────

/// <summary>Tests for the Tag model: properties, defaults, and initialization.</summary>
public class TagModelTests
{
    private static Tag Make(string name = "landscape") => new()
    {
        Name           = name,
        NormalizedName = name.ToLowerInvariant(),
    };

    [Fact]
    public void Id_AutoGeneratedAndNotEmpty()
        => Assert.NotEqual(Guid.Empty, Make().Id);

    [Fact]
    public void TwoTags_HaveDifferentIds()
        => Assert.NotEqual(Make().Id, Make().Id);

    [Fact]
    public void Category_DefaultIsGeneral()
        => Assert.Equal(TagCategory.General, Make().Category);

    [Fact]
    public void IsAIGenerated_DefaultIsFalse()
        => Assert.False(Make().IsAIGenerated);

    [Fact]
    public void Confidence_DefaultIsNull()
        => Assert.Null(Make().Confidence);

    [Fact]
    public void Color_DefaultIsNull()
        => Assert.Null(Make().Color);

    [Fact]
    public void DateCreated_DefaultIsRecentUtcTimestamp()
    {
        var before = DateTime.UtcNow.AddSeconds(-2);
        var tag    = Make();
        var after  = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(tag.DateCreated, before, after);
    }

    [Fact]
    public void MediaFiles_InitialisedToEmptyCollection()
    {
        var tag = Make();
        Assert.NotNull(tag.MediaFiles);
        Assert.Empty(tag.MediaFiles);
    }

    [Fact]
    public void Name_RoundTrips()
    {
        var tag = Make("sunset");
        Assert.Equal("sunset", tag.Name);
    }

    [Fact]
    public void NormalizedName_RoundTrips()
    {
        var tag = Make("Forest");
        Assert.Equal("forest", tag.NormalizedName);
    }

    [Theory]
    [InlineData(true)]
    [InlineData(false)]
    public void IsAIGenerated_CanBeSetToEitherValue(bool value)
    {
        var tag = Make();
        tag.IsAIGenerated = value;
        Assert.Equal(value, tag.IsAIGenerated);
    }

    [Fact]
    public void Confidence_CanBeSetToDoubleValue()
    {
        var tag = Make();
        tag.Confidence = 0.87;
        Assert.Equal(0.87, tag.Confidence);
    }

    [Fact]
    public void Color_CanBeSet()
    {
        var tag = Make();
        tag.Color = "#FF5733";
        Assert.Equal("#FF5733", tag.Color);
    }

    [Theory]
    [InlineData(TagCategory.Object)]
    [InlineData(TagCategory.Scene)]
    [InlineData(TagCategory.Activity)]
    [InlineData(TagCategory.Color)]
    [InlineData(TagCategory.Style)]
    [InlineData(TagCategory.Emotion)]
    [InlineData(TagCategory.Person)]
    public void Category_CanBeSetToNonDefaultValues(TagCategory cat)
    {
        var tag = Make();
        tag.Category = cat;
        Assert.Equal(cat, tag.Category);
    }
}

// ── TagCategory enum ──────────────────────────────────────────────────────────

/// <summary>Tests for the TagCategory enum and its values.</summary>
public class TagCategoryEnumTests
{
    [Fact]
    public void TagCategory_HasExactly12Values()
        => Assert.Equal(12, Enum.GetValues<TagCategory>().Length);

    [Fact]
    public void TagCategory_ContainsAllExpectedMembers()
    {
        var values = Enum.GetValues<TagCategory>();
        Assert.Contains(TagCategory.General,  values);
        Assert.Contains(TagCategory.Object,   values);
        Assert.Contains(TagCategory.Scene,    values);
        Assert.Contains(TagCategory.Activity, values);
        Assert.Contains(TagCategory.Color,    values);
        Assert.Contains(TagCategory.Style,    values);
        Assert.Contains(TagCategory.Emotion,  values);
        Assert.Contains(TagCategory.Text,     values);
        Assert.Contains(TagCategory.Location, values);
        Assert.Contains(TagCategory.Event,    values);
        Assert.Contains(TagCategory.Person,   values);
        Assert.Contains(TagCategory.Custom,   values);
    }

    [Fact]
    public void TagCategory_General_IsZero()
        => Assert.Equal(0, (int)TagCategory.General);
}

// ── Library model ─────────────────────────────────────────────────────────────

/// <summary>Tests for the Library model: properties, defaults, and album hierarchy.</summary>
public class LibraryModelTests
{
    private static Library Make(string name = "My Library") => new() { Name = name };

    [Fact]
    public void Id_AutoGeneratedAndNotEmpty()
        => Assert.NotEqual(Guid.Empty, Make().Id);

    [Fact]
    public void TwoInstances_HaveDifferentIds()
        => Assert.NotEqual(Make().Id, Make().Id);

    [Fact]
    public void Description_DefaultIsNull()
        => Assert.Null(Make().Description);

    [Fact]
    public void CreatedAt_DefaultIsRecentUtcTimestamp()
    {
        var before = DateTime.UtcNow.AddSeconds(-2);
        var lib    = Make();
        var after  = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(lib.CreatedAt, before, after);
    }

    [Fact]
    public void Albums_InitialisedToEmptyCollection()
    {
        var lib = Make();
        Assert.NotNull(lib.Albums);
        Assert.Empty(lib.Albums);
    }

    [Fact]
    public void Name_RoundTrips()
        => Assert.Equal("Vacations 2024", Make("Vacations 2024").Name);

    [Fact]
    public void Description_CanBeSet()
    {
        var lib = Make();
        lib.Description = "Summer photos";
        Assert.Equal("Summer photos", lib.Description);
    }
}

// ── Album model ───────────────────────────────────────────────────────────────

/// <summary>Tests for the Album model: properties, defaults, and photo collection.</summary>
public class AlbumModelTests
{
    private static Album Make(string name = "Paris Trip") => new()
    {
        Name      = name,
        LibraryId = Guid.NewGuid(),
    };

    [Fact]
    public void Id_AutoGeneratedAndNotEmpty()
        => Assert.NotEqual(Guid.Empty, Make().Id);

    [Fact]
    public void TwoInstances_HaveDifferentIds()
        => Assert.NotEqual(Make().Id, Make().Id);

    [Fact]
    public void CoverPhotoId_DefaultIsNull()
        => Assert.Null(Make().CoverPhotoId);

    [Fact]
    public void Description_DefaultIsNull()
        => Assert.Null(Make().Description);

    [Fact]
    public void CreatedAt_DefaultIsRecentUtcTimestamp()
    {
        var before = DateTime.UtcNow.AddSeconds(-2);
        var album  = Make();
        var after  = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(album.CreatedAt, before, after);
    }

    [Fact]
    public void MediaFiles_InitialisedToEmptyCollection()
    {
        var album = Make();
        Assert.NotNull(album.MediaFiles);
        Assert.Empty(album.MediaFiles);
    }

    [Fact]
    public void Name_RoundTrips()
        => Assert.Equal("Wedding 2025", Make("Wedding 2025").Name);

    [Fact]
    public void CoverPhotoId_CanBeSet()
    {
        var id    = Guid.NewGuid();
        var album = Make();
        album.CoverPhotoId = id;
        Assert.Equal(id, album.CoverPhotoId);
    }

    [Fact]
    public void LibraryId_RoundTrips()
    {
        var libId = Guid.NewGuid();
        var album = new Album { Name = "Test", LibraryId = libId };
        Assert.Equal(libId, album.LibraryId);
    }
}

// ── ExclusionRule model ───────────────────────────────────────────────────────

/// <summary>Tests for the ExclusionRule model: folder/path exclusion rules.</summary>
public class ExclusionRuleModelTests
{
    [Fact]
    public void Id_DefaultIsZero_IntKey()
        => Assert.Equal(0, new ExclusionRule().Id);

    [Fact]
    public void Value_DefaultIsEmptyString()
        => Assert.Equal("", new ExclusionRule().Value);

    [Fact]
    public void IsFullPath_DefaultIsFalse()
        => Assert.False(new ExclusionRule().IsFullPath);

    [Fact]
    public void Value_CanBeSet()
    {
        var rule = new ExclusionRule { Value = @"C:\Windows\Temp" };
        Assert.Equal(@"C:\Windows\Temp", rule.Value);
    }

    [Fact]
    public void IsFullPath_CanBeSetToTrue()
    {
        var rule = new ExclusionRule { IsFullPath = true };
        Assert.True(rule.IsFullPath);
    }

    [Fact]
    public void Value_CanStoreUpTo500Characters()
    {
        var longValue = new string('x', 500);
        var rule      = new ExclusionRule { Value = longValue };
        Assert.Equal(500, rule.Value.Length);
    }

    [Theory]
    [InlineData("node_modules", false)]
    [InlineData(@"C:\Users\photos\Private", true)]
    [InlineData(".git", false)]
    [InlineData("Thumbs.db", false)]
    public void IsFullPath_And_Value_RoundTripTogether(string value, bool isFullPath)
    {
        var rule = new ExclusionRule { Value = value, IsFullPath = isFullPath };
        Assert.Equal(value, rule.Value);
        Assert.Equal(isFullPath, rule.IsFullPath);
    }
}

// ── Face model ────────────────────────────────────────────────────────────────

/// <summary>Tests for the Face model: detection results, embeddings, and person linking.</summary>
public class FaceModelTests
{
    private static Face Make() => new() { MediaFileId = Guid.NewGuid() };

    [Fact]
    public void Id_AutoGeneratedAndNotEmpty()
        => Assert.NotEqual(Guid.Empty, Make().Id);

    [Fact]
    public void TwoInstances_HaveDifferentIds()
        => Assert.NotEqual(Make().Id, Make().Id);

    [Fact]
    public void PersonId_DefaultIsNull()
        => Assert.Null(Make().PersonId);

    [Fact]
    public void Embedding_DefaultIsNull()
        => Assert.Null(Make().Embedding);

    [Fact]
    public void IdentificationConfidence_DefaultIsNull()
        => Assert.Null(Make().IdentificationConfidence);

    [Fact]
    public void ThumbnailPath_DefaultIsNull()
        => Assert.Null(Make().ThumbnailPath);

    [Fact]
    public void DateDetected_DefaultIsRecentUtcTimestamp()
    {
        var before = DateTime.UtcNow.AddSeconds(-2);
        var face   = Make();
        var after  = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(face.DateDetected, before, after);
    }

    [Fact]
    public void BoundingBox_DefaultsToZero()
    {
        var face = Make();
        Assert.Equal(0.0, face.X);
        Assert.Equal(0.0, face.Y);
        Assert.Equal(0.0, face.Width);
        Assert.Equal(0.0, face.Height);
    }

    [Fact]
    public void BoundingBox_CanBeSet()
    {
        var face = new Face
        {
            MediaFileId = Guid.NewGuid(),
            X      = 0.10,
            Y      = 0.20,
            Width  = 0.30,
            Height = 0.40,
        };
        Assert.Equal(0.10, face.X);
        Assert.Equal(0.20, face.Y);
        Assert.Equal(0.30, face.Width);
        Assert.Equal(0.40, face.Height);
    }

    [Fact]
    public void DetectionConfidence_CanBeSet()
    {
        var face = Make();
        face.DetectionConfidence = 0.98;
        Assert.Equal(0.98, face.DetectionConfidence);
    }

    [Fact]
    public void Embedding_CanBeSet()
    {
        var face = Make();
        face.Embedding = new byte[] { 1, 2, 3, 4 };
        Assert.Equal(4, face.Embedding.Length);
    }
}

// ── Person model ──────────────────────────────────────────────────────────────

/// <summary>Tests for the Person model: identified people, face counts, and embeddings.</summary>
public class PersonModelTests
{
    private static Person Make() => new();

    [Fact]
    public void Id_AutoGeneratedAndNotEmpty()
        => Assert.NotEqual(Guid.Empty, Make().Id);

    [Fact]
    public void TwoInstances_HaveDifferentIds()
        => Assert.NotEqual(Make().Id, Make().Id);

    [Fact]
    public void Name_DefaultIsNull()
        => Assert.Null(Make().Name);

    [Fact]
    public void NormalizedName_DefaultIsNull()
        => Assert.Null(Make().NormalizedName);

    [Fact]
    public void IsNamed_DefaultIsFalse()
        => Assert.False(Make().IsNamed);

    [Fact]
    public void IsVisible_DefaultIsTrue()
        => Assert.True(Make().IsVisible);

    [Fact]
    public void IsFavorite_DefaultIsFalse()
        => Assert.False(Make().IsFavorite);

    [Fact]
    public void KeyFaceId_DefaultIsNull()
        => Assert.Null(Make().KeyFaceId);

    [Fact]
    public void AverageEmbedding_DefaultIsNull()
        => Assert.Null(Make().AverageEmbedding);

    [Fact]
    public void DateCreated_DefaultIsRecentUtcTimestamp()
    {
        var before  = DateTime.UtcNow.AddSeconds(-2);
        var person  = Make();
        var after   = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(person.DateCreated, before, after);
    }

    [Fact]
    public void DateModified_DefaultIsRecentUtcTimestamp()
    {
        var before  = DateTime.UtcNow.AddSeconds(-2);
        var person  = Make();
        var after   = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(person.DateModified, before, after);
    }

    [Fact]
    public void Faces_InitialisedToEmptyCollection()
    {
        var person = Make();
        Assert.NotNull(person.Faces);
        Assert.Empty(person.Faces);
    }

    [Fact]
    public void Name_CanBeSet()
    {
        var person = Make();
        person.Name           = "Alice";
        person.NormalizedName = "alice";
        Assert.Equal("Alice", person.Name);
        Assert.Equal("alice", person.NormalizedName);
    }

    [Fact]
    public void IsVisible_CanBeSetToFalse()
    {
        var person = Make();
        person.IsVisible = false;
        Assert.False(person.IsVisible);
    }
}

// ── AnalysisMetric model ──────────────────────────────────────────────────────

/// <summary>Tests for the AnalysisMetric model: performance metrics and timing data.</summary>
public class AnalysisMetricModelTests
{
    private static AnalysisMetric Make() => new() { PhotoId = Guid.NewGuid() };

    [Fact]
    public void Id_AutoGeneratedAndNotEmpty()
        => Assert.NotEqual(Guid.Empty, Make().Id);

    [Fact]
    public void TwoInstances_HaveDifferentIds()
        => Assert.NotEqual(Make().Id, Make().Id);

    [Fact]
    public void ModelName_DefaultIsEmptyString()
        => Assert.Equal("", Make().ModelName);

    [Fact]
    public void FileFormat_DefaultIsEmptyString()
        => Assert.Equal("", Make().FileFormat);

    [Fact]
    public void GpuUsed_DefaultIsFalse()
        => Assert.False(Make().GpuUsed);

    [Fact]
    public void NumericFields_DefaultToZero()
    {
        var m = Make();
        Assert.Equal(0, m.ImageWidth);
        Assert.Equal(0, m.ImageHeight);
        Assert.Equal(0L, m.FileSizeBytes);
        Assert.Equal(0L, m.PreprocessingMs);
        Assert.Equal(0L, m.InferenceMs);
        Assert.Equal(0L, m.TotalAnalysisMs);
        Assert.Equal(0, m.TagCount);
        Assert.Equal(0, m.DescriptionLength);
    }

    [Fact]
    public void AnalyzedAt_DefaultIsRecentUtcTimestamp()
    {
        var before = DateTime.UtcNow.AddSeconds(-2);
        var m      = Make();
        var after  = DateTime.UtcNow.AddSeconds(2);
        Assert.InRange(m.AnalyzedAt, before, after);
    }

    [Fact]
    public void AllFields_CanBeSet()
    {
        var photoId = Guid.NewGuid();
        var m = new AnalysisMetric
        {
            PhotoId           = photoId,
            ModelName         = "llama3.2-vision",
            ImageWidth        = 3840,
            ImageHeight       = 2160,
            FileFormat        = "jpg",
            FileSizeBytes     = 4_500_000L,
            PreprocessingMs   = 45L,
            InferenceMs       = 3200L,
            TotalAnalysisMs   = 3250L,
            TagCount          = 12,
            DescriptionLength = 187,
            GpuUsed           = true,
        };

        Assert.Equal(photoId,         m.PhotoId);
        Assert.Equal("llama3.2-vision", m.ModelName);
        Assert.Equal(3840,            m.ImageWidth);
        Assert.Equal(2160,            m.ImageHeight);
        Assert.Equal("jpg",           m.FileFormat);
        Assert.Equal(4_500_000L,      m.FileSizeBytes);
        Assert.Equal(45L,             m.PreprocessingMs);
        Assert.Equal(3200L,           m.InferenceMs);
        Assert.Equal(3250L,           m.TotalAnalysisMs);
        Assert.Equal(12,              m.TagCount);
        Assert.Equal(187,             m.DescriptionLength);
        Assert.True(m.GpuUsed);
    }

    [Fact]
    public void PhotoId_CanBeSetToNonEmptyGuid()
    {
        var id = Guid.NewGuid();
        var m  = new AnalysisMetric { PhotoId = id };
        Assert.Equal(id, m.PhotoId);
    }
}
